#!/bin/bash
# Copyright (C) 2022 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

set -e

JOBS=6

failure() {
    test ${#@} -eq 0 || echo "$(basename "$0"):" "$@" >&2
    exit 1
}

usage() {
    echo "usage: $(basename "$0") [OPTION]..."
    echo "Run the CI pipeline or parts of it."
    echo
    echo "  -c, --clean             remove artifacts first"
    echo "  -u, --unit-tests        run unit tests"
    echo "  -F, --check-format      check for correct formatting"
    echo "  -m, --mypy              run mypy"
    echo "  -p, --pylint            run pylint"
    echo "  -B, --bandit            run bandit"
    echo "  -E, --e2e               run end-to-end tests"
    echo "  -a, --all               shortcut for -u -F -m -p -B -C"
    echo "  -f, --format            format sources"
    echo "  -D, --documentation     generate documentation"
    echo "  -j N, --jobs=N          allow N jobs at once, default is ${JOBS}"
    echo "  -h, --help              show this help"
}

parse_options() {
    # Yes, all those option variables are global.
    RUN_CLEAN=no
    RUN_UNIT_TESTS=no
    RUN_CHECK_FORMAT=no
    RUN_MYPY=no
    RUN_PYLINT=no
    RUN_BANDIT=no
    RUN_E2E=no
    RUN_FORMAT=no
    RUN_DOCUMENTATION=no

    if ! OPTIONS=$(getopt --options 'cuFmpBEafDj:h' --long 'clean,unit-tests,check-format,mypy,pylint,bandit,e2e,all,format,documentation,jobs:,help' --name "$(basename "$0")" -- "$@"); then
        usage >&2
        failure
    fi
    eval set -- "$OPTIONS"
    unset OPTIONS

    while true; do
        case "$1" in
            '-c' | '--clean')
                RUN_CLEAN=yes
                shift
                continue
                ;;
            '-u' | '--unit-tests')
                RUN_UNIT_TESTS=yes
                shift
                continue
                ;;
            '-F' | '--check-format')
                RUN_CHECK_FORMAT=yes
                shift
                continue
                ;;
            '-m' | '--mypy')
                RUN_MYPY=yes
                shift
                continue
                ;;
            '-p' | '--pylint')
                RUN_PYLINT=yes
                shift
                continue
                ;;
            '-B' | '--bandit')
                RUN_BANDIT=yes
                shift
                continue
                ;;
            '-E' | '--e2e')
                RUN_E2E=yes
                shift
                continue
                ;;
            '-a' | '--all')
                RUN_UNIT_TESTS=yes
                RUN_CHECK_FORMAT=yes
                RUN_MYPY=yes
                RUN_PYLINT=yes
                RUN_BANDIT=yes
                RUN_E2E=yes
                shift
                continue
                ;;
            '-f' | '--format')
                RUN_FORMAT=yes
                shift
                continue
                ;;
            '-D' | '--documentation')
                RUN_DOCUMENTATION=yes
                shift
                continue
                ;;
            '-j' | '--jobs')
                JOBS="$2"
                shift 2
                continue
                ;;
            '-h' | '--help')
                usage
                exit 0
                ;;
            '--')
                shift
                test ${#@} -eq 0 || failure "extra arguments:" "$@"
                break
                ;;
            *) failure "internal error" ;;
        esac
    done

    readonly RUN_CLEAN RUN_UNIT_TESTS RUN_CHECK_FORMAT RUN_MYPY RUN_PYLINT RUN_BANDIT RUN_E2E RUN_FORMAT RUN_DOCUMENTATION JOBS
}

run_clean() {
    rm -rf .cache .mypy_cache .pytest_cache .venv ./*.egg-info build
    find py_import_cycles tests -type d -name __pycache__ -print0 | xargs --null --no-run-if-empty rm -rf
}

run_unit_tests() {
    uv run pytest
}

run_check_format() {
    uv run black --config pyproject.toml --check --diff py_import_cycles tests
    uv run isort --settings-path pyproject.toml --check-only --diff py_import_cycles tests
}

run_mypy() {
    uv run mypy py_import_cycles tests
}

run_pylint() {
    uv run pylint --jobs="${JOBS}" py_import_cycles tests
}

run_bandit() {
    # We would like to put everything into pyproject.toml, so running just "bandit" would do the
    # right thing. But bandit is totally obscure & complicated regarding configuration, see several
    # issues like https://github.com/PyCQA/bandit/issues/606.  :-/
    uv run bandit --configfile=pyproject.toml --quiet --recursive --severity-level=medium py_import_cycles tests
}

run_e2e() {
    ./scripts/run-e2e-tests
}

run_format() {
    uv run black --config pyproject.toml py_import_cycles tests
    uv run isort --settings-path pyproject.toml py_import_cycles tests
}

run_documentation() {
    echo "TODO: generate documentation"
}

main() {
    # Change to the directory where this script resides, it makes many things easier
    # and we can call this script from everywhere.
    cd -- "${BASH_SOURCE%/*}"
    parse_options "$@"
    test ${RUN_CLEAN} = yes && run_clean
    test ${RUN_UNIT_TESTS} = yes && run_unit_tests
    test ${RUN_CHECK_FORMAT} = yes && run_check_format
    test ${RUN_MYPY} = yes && run_mypy
    test ${RUN_PYLINT} = yes && run_pylint
    test ${RUN_BANDIT} = yes && run_bandit
    test ${RUN_E2E} = yes && run_e2e
    test ${RUN_DOCUMENTATION} = yes && run_documentation
    test ${RUN_FORMAT} = yes && run_format
    true
}

main "$@"
