#!/bin/bash

REPO_PATH=$(dirname "$(dirname "$(realpath "$0")")")
run_pipenv=$REPO_PATH/scripts/run-pipenv

if [ -n "$1" ]; then
	python_files="$1"
else
	python_files="$("$REPO_PATH/scripts/find-python-files")"
fi

# shellcheck disable=SC2086
reformatted_files=$($run_pipenv black "$@" $python_files 2>&1 | grep "^reformatted\|^would reformat")
if [ -n "$reformatted_files" ]; then
    echo -e "$reformatted_files"
    exit 1
fi
