#!/bin/bash

REPO_PATH=$(dirname "$(dirname "$(realpath "$0")")")

if [ "$PIPENV_ACTIVE" != "1" ]; then
    echo "Run pylint within pipenv"
    exit 1
fi

if [ -n "$1" ]; then
	python_files="$1"
else
	python_files="$("$REPO_PATH/scripts/find-python-files" --pylint)"
fi

if [ -z "$python_files" ]; then
    exit 0
fi

# shellcheck disable=SC2086
pipenv run pylint \
    --rcfile=../.pylintrc \
    $python_files
