#!/bin/bash

REPO_PATH=$(dirname "$(dirname "$(realpath "$0")")")

python_files=$("${REPO_PATH}"/scripts/find-python-files)
if [ -z "$python_files" ]; then
    exit 0
fi

# shellcheck disable=SC2086
exec "$REPO_PATH/scripts/run-pipenv" run pylint \
    --rcfile="$REPO_PATH"/.pylintrc \
    $python_files
