#!/bin/bash

REPO_PATH=$(dirname "$(dirname "$(realpath "$0")")")

python_files=$("${REPO_PATH}"/scripts/find-python-files)
if [ -z "$python_files" ]; then
    exit 0
fi

# shellcheck disable=SC2086
reformatted_files=$(
    "$REPO_PATH/scripts/run-pipenv" run black \
    --settings-path "$REPO_PATH"/pyproject.toml \
    "$@" $python_files 2>&1 |\
    grep "^reformatted\|^would reformat"
)

if [ -n "$reformatted_files" ]; then
    echo -e "$reformatted_files"
    exit 1
fi
