#!/bin/bash

REPO_PATH=$(dirname "$(dirname "$(realpath "$0")")")

if [ "$PIPENV_ACTIVE" != "1" ]; then
    echo "Run isort within pipenv"
    exit 1
fi

if [ -n "$1" ]; then
	python_files="$1"
else
	python_files="$("$REPO_PATH/scripts/find-python-files")"
fi

# shellcheck disable=SC2086
output=$(pipenv run isort --diff "$@" $python_files 2>&1)
if [ -n "$output" ]; then
    echo -e "$output"
    exit 1
fi
