#!/bin/bash

REPO_PATH=$(dirname "$(dirname "$(realpath "$0")")")

echo "===== Cleanup pycache ====="
find "${REPO_PATH}/e2e_test_inputs" -name __pycache__ -exec rm -rf {} \+

cd "$REPO_PATH" || exit 1

for project in ./e2e_test_inputs/*; do
    project=${project#./}

    echo "===== Test $project ====="
    if [ -f "$REPO_PATH/$project/skip_main" ]; then
        echo "Skip testing main due to:"
        cat "$REPO_PATH/$project/skip_main"
    else
        echo "Test main..."
        pipenv run python3 "$project/main.py" 1>/dev/null || { echo "Test $project failed (execution of main)." >&2; exit 1; }
    fi

    num_cycles="$(cat "$REPO_PATH/$project"/found_cycles)"

    echo "Test cycles (--packages)..."
    packages=""
    while read -r line; do
        for word in $line; do
            packages="$packages $REPO_PATH/$project/$word"
        done
    done <"$REPO_PATH/$project"/packages

    # shellcheck disable=SC2086
    pkgs_result=$(PYTHONPATH="." ./run-main --packages $packages --strategy johnson 2>&1)
    if [ "$pkgs_result" != "Found $num_cycles import cycles" ]; then
        echo "Test '--packages' $project failed (expect $num_cycles cycles, got '$pkgs_result')." >&2
        echo "Run 'PYTHONPATH=\".\" ./run-main  --packages $packages --strategy johnson'" >&2
        exit 1
    fi

    echo "Test cycles (--files, absolute)..."
    abs_files=""
    while read -r line; do
        for word in $line; do
            abs_files="$abs_files $REPO_PATH/$project::$word"
        done
    done <"$REPO_PATH/$project"/files

    # shellcheck disable=SC2086
    abs_files_result=$(PYTHONPATH="." ./run-main --files $abs_files --strategy johnson 2>&1)
    if [ "$abs_files_result" != "Found $num_cycles import cycles" ]; then
        echo "Test '--files, absolute' $project failed (expect $num_cycles cycles, got '$abs_files_result')." >&2
        echo "Run 'PYTHONPATH=\".\" ./run-main --files $abs_files --strategy johnson'" >&2
        exit 1
    fi

    echo "Test cycles (--files, relative)..."
    rel_files=""
    while read -r line; do
        for word in $line; do
            rel_files="$rel_files $project::$word"
        done
    done <"$REPO_PATH/$project"/files

    # shellcheck disable=SC2086
    rel_files_result=$(PYTHONPATH="." ./run-main --files $rel_files --strategy johnson 2>&1)
    if [ "$rel_files_result" != "Found $num_cycles import cycles" ]; then
        echo "Test '--files, relative' $project failed (expect $num_cycles cycles, got '$rel_files_result')." >&2
        echo "Run 'PYTHONPATH=\".\" ./run-main --files $rel_files --strategy johnson'" >&2
        exit 1
    fi
done

echo "===== Self test ====="
echo "Test cycles..."

result=$(PYTHONPATH="." ./run-main --packages "$REPO_PATH/py_import_cycles" --strategy johnson 2>&1)
if [ "$result" != "Found 0 import cycles" ]; then
    echo "Self test failed (expect 0 cycles, got '$result')." >&2
    exit 1
fi
