name: main

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install pipenv
        run: python -m pip install --user pipenv
      - name: Install deps
        run: pipenv install && pipenv install --dev
      - name: QA
        run: |
          ./scripts/run-black --check
          ./scripts/run-isort --check
          ./scripts/run-mypy
          ./scripts/run-pylint
          ./scripts/run-shellcheck
      - name: Test
        run: pipenv run pytest tests
      - name: Projects
        run: ./scripts/run-projects
