name: test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:


jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: run pytest
        run: uv run pytest .

  all-checks:
    if: ${{ !cancelled() }}
    needs: [pytest]
    runs-on: ubuntu-latest
    steps:
      - if: >-
          ${{ contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled') }}
        run: exit 1
